# network architecture
arch: "resnet50"
# number of workers
workers: 4
# starting epoch
start_epoch: 0
# learing rate schedule hyper parameters
schedule: [120, 160]
# optimizer momentum
momentum: 0.9
# optimizer weight decay
weight_decay: 0.0001
# print frequency of model
print_freq: 5
resume: True
world_size: 1
rank: 0
dist_url: "tcp://localhost:10005"
dist_backend: "nccl"
seed: null
multiprocessing_distributed: True
gpu: null
dim: 512
moco_m: 0.999
temperature: 0.2
mlp: True
aug_plus: True
cos: True
warmup_epoch: 20
input_image_width: 224
input_image_height: 224
pretrained: True