eval_gpu: 3
encoder: "query"
output_layer: "fc"
num_classes: 100
label_percent: 0.1
weight_decay: 0
momentum: 0.9
print_freq: 5
resume: True
random_init: False
data_augmentation: True
scheduler:
  use: True
  type: "linear"
  linear: 
    gamma: 0.1
    ms:
      - 50
      - 200
  cosine: 
    T_0: 125
    T_mult: 1
temperature: 1.0
unfreeze_epoch: 50